import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/components/servers/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mordern Parking W-APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
